import { createECDH } from "node:crypto";
import { chmodSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, statSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";

import { ConfigureEngineRefusal } from "./configure-engine";
import { VAPID_PRIVATE_KEY_RUNTIME_PATH, ensureVapidKeys, generateVapidKeyPair } from "./vapid-keys";

// #1210 D7: VAPID keys are generated by the engine (configure.sh guarantees
// #24-26, formerly ensure_vapid_keys and a Docker-built helper image).

let deployDir: string;
const keyPath = (): string => join(deployDir, ".orbit-secrets", "vapid-private-key");
const envPath = (): string => join(deployDir, ".env-orbit");

beforeEach(() => {
  deployDir = mkdtempSync(join(tmpdir(), "orbit-vapid-"));
  writeFileSync(envPath(), "APP_URL=https://orbit.vapid.invalid\nVAPID_PUBLIC_KEY=\nVAPID_PRIVATE_KEY_FILE=\n", { mode: 0o600 });
});

afterEach(() => {
  rmSync(deployDir, { recursive: true, force: true });
});

describe("generateVapidKeyPair", () => {
  it("returns a usable P-256 pair in unpadded base64url", () => {
    const pair = generateVapidKeyPair();
    expect(pair.publicKey).toMatch(/^[A-Za-z0-9_-]{87}$/); // 65-byte uncompressed point
    expect(pair.privateKey).toMatch(/^[A-Za-z0-9_-]{43}$/); // 32-byte scalar
    const ecdh = createECDH("prime256v1");
    ecdh.setPrivateKey(Buffer.from(pair.privateKey, "base64url"));
    expect(ecdh.getPublicKey().toString("base64url")).toBe(pair.publicKey);
  });

  // Node's ECDH returns the private scalar without leading zero bytes, so about
  // one key in 256 comes back 31 bytes long, and web-push refuses any VAPID
  // private key that is not exactly 32. 3000 draws make such a key all but
  // certain to appear (1 - (255/256)^3000 > 0.9999).
  it("always encodes the private key as the full 32 bytes", () => {
    for (let draw = 0; draw < 3000; draw += 1) {
      expect(Buffer.from(generateVapidKeyPair().privateKey, "base64url")).toHaveLength(32);
    }
  });

  it("is random", () => {
    expect(generateVapidKeyPair().privateKey).not.toBe(generateVapidKeyPair().privateKey);
  });
});

describe("ensureVapidKeys", () => {
  it("generates a pair, writes the private key at 600 and records both keys (#24-26)", () => {
    const result = ensureVapidKeys(deployDir, () => ({ publicKey: "pub-fixture", privateKey: "priv-fixture" }));
    expect(result).toEqual({ generated: true, message: "Generated VAPID push keys." });
    expect(readFileSync(keyPath(), "utf8")).toBe("priv-fixture\n");
    expect(statSync(keyPath()).mode & 0o777).toBe(0o600);
    expect(statSync(join(deployDir, ".orbit-secrets")).mode & 0o777).toBe(0o700);
    const env = readFileSync(envPath(), "utf8");
    expect(env).toContain("VAPID_PUBLIC_KEY=pub-fixture\n");
    expect(env).toContain(`VAPID_PRIVATE_KEY_FILE=${VAPID_PRIVATE_KEY_RUNTIME_PATH}\n`);
    expect(readdirSync(join(deployDir, ".orbit-secrets")).filter((name) => name.startsWith("."))).toEqual([]);
  });

  it("keeps an existing non-empty key and never touches .env-orbit", () => {
    mkdirSync(join(deployDir, ".orbit-secrets"), { mode: 0o700 });
    writeFileSync(keyPath(), "existing\n", { mode: 0o644 });
    const before = readFileSync(envPath(), "utf8");
    const result = ensureVapidKeys(deployDir, () => {
      throw new Error("must not generate");
    });
    expect(result).toEqual({ generated: false });
    expect(readFileSync(keyPath(), "utf8")).toBe("existing\n");
    expect(statSync(keyPath()).mode & 0o777).toBe(0o600);
    expect(readFileSync(envPath(), "utf8")).toBe(before);
  });

  it("replaces an empty key file", () => {
    mkdirSync(join(deployDir, ".orbit-secrets"), { mode: 0o700 });
    writeFileSync(keyPath(), "", { mode: 0o600 });
    expect(ensureVapidKeys(deployDir).generated).toBe(true);
    expect(readFileSync(keyPath(), "utf8")).toMatch(/^[A-Za-z0-9_-]{43}\n$/);
  });

  it("refuses a symlinked key path rather than following it", () => {
    mkdirSync(join(deployDir, ".orbit-secrets"), { mode: 0o700 });
    const elsewhere = join(deployDir, "elsewhere");
    writeFileSync(elsewhere, "x\n");
    chmodSync(elsewhere, 0o644);
    symlinkSync(elsewhere, keyPath());
    expect(() => ensureVapidKeys(deployDir)).toThrow(ConfigureEngineRefusal);
    expect(statSync(elsewhere).mode & 0o777).toBe(0o644);
  });
});
