events {}
http {
  server {
    listen 3443 ssl;
    ssl_certificate /etc/demo/demo.crt;
    ssl_certificate_key /etc/demo/demo.key;
    location / {
      proxy_pass http://orbit:3000;
      proxy_set_header Host $host:3443;
      proxy_http_version 1.1;
    }
  }
}
