import { deflateSync } from "node:zlib";

/** Synthetic structure fixtures generated by local code; not common-producer output. */

interface PdfObject {
  id: number;
  generation?: number;
  body: Buffer;
}

interface ClassicPdfBuild {
  bytes: Buffer;
  xrefOffset: number;
}

function text(value: string): Buffer {
  return Buffer.from(value, "latin1");
}

function object(id: number, body: Buffer | string, generation = 0): PdfObject {
  return { id, generation, body: typeof body === "string" ? text(body) : body };
}

function streamObject(dictionary: string, body: Buffer): Buffer {
  return Buffer.concat([
    text(`<< ${dictionary} >>\nstream\n`),
    body,
    text("\nendstream"),
  ]);
}

function pageObjects(contents: PdfObject): PdfObject[] {
  return [
    object(1, "<< /Type /Catalog /Pages 2 0 R >>"),
    object(2, "<< /Type /Pages /Kids [3 0 R] /Count 1 >>"),
    object(3, `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents ${contents.id} 0 R >>`),
    object(4, "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"),
    contents,
  ];
}

function pageContent(value = "Generated PDF producer fixture"): Buffer {
  const escaped = value.replaceAll("\\", "\\\\").replaceAll("(", "\\(").replaceAll(")", "\\)");
  return text(`BT /F1 18 Tf 72 720 Td (${escaped}) Tj ET`);
}

function buildClassicPdf(objects: PdfObject[], root = "1 0 R"): ClassicPdfBuild {
  const ordered = [...objects].sort((left, right) => left.id - right.id);
  const offsets = new Map<number, number>([[0, 0]]);
  let bytes = text("%PDF-1.7\n");
  for (const entry of ordered) {
    offsets.set(entry.id, bytes.length);
    bytes = Buffer.concat([
      bytes,
      text(`${entry.id} ${entry.generation ?? 0} obj\n`),
      entry.body,
      text("\nendobj\n"),
    ]);
  }
  const size = Math.max(...ordered.map(({ id }) => id)) + 1;
  const xrefOffset = bytes.length;
  let xref = `xref\n0 ${size}\n0000000000 65535 f \n`;
  for (let id = 1; id < size; id += 1) {
    const offset = offsets.get(id);
    if (offset === undefined) throw new Error(`fixture object ${id} is missing`);
    const generation = ordered.find((entry) => entry.id === id)?.generation ?? 0;
    xref += `${String(offset).padStart(10, "0")} ${String(generation).padStart(5, "0")} n \n`;
  }
  bytes = Buffer.concat([
    bytes,
    text(xref),
    text(`trailer\n<< /Size ${size} /Root ${root} >>\nstartxref\n${xrefOffset}\n%%EOF\n`),
  ]);
  return { bytes, xrefOffset };
}

function xrefEntry(type: number, field2: number, field3: number): Buffer {
  const entry = Buffer.alloc(7);
  entry[0] = type;
  entry.writeUInt32BE(field2, 1);
  entry.writeUInt16BE(field3, 5);
  return entry;
}

function buildXrefStreamPdf(objects: PdfObject[], xrefObjectId: number): Buffer {
  let bytes = text("%PDF-1.7\n");
  const offsets = new Map<number, number>();
  for (const entry of [...objects].sort((left, right) => left.id - right.id)) {
    offsets.set(entry.id, bytes.length);
    bytes = Buffer.concat([
      bytes,
      text(`${entry.id} ${entry.generation ?? 0} obj\n`),
      entry.body,
      text("\nendobj\n"),
    ]);
  }
  const xrefOffset = bytes.length;
  const entries = [xrefEntry(0, 0, 65535)];
  for (let id = 1; id <= xrefObjectId; id += 1) {
    entries.push(xrefEntry(1, id === xrefObjectId ? xrefOffset : offsets.get(id)!, 0));
  }
  const compressedEntries = deflateSync(Buffer.concat(entries));
  const dictionary = `/Type /XRef /Size ${xrefObjectId + 1} /Root 1 0 R /W [1 4 2] /Index [0 ${xrefObjectId + 1}] /Length ${compressedEntries.length} /Filter /FlateDecode`;
  const xrefObject = object(xrefObjectId, streamObject(dictionary, compressedEntries));
  bytes = Buffer.concat([
    bytes,
    text(`${xrefObject.id} 0 obj\n`),
    xrefObject.body,
    text("\nendobj\n"),
    text(`startxref\n${xrefOffset}\n%%EOF\n`),
  ]);
  if (offsets.size !== xrefObjectId - 1) throw new Error("fixture object numbering is not contiguous");
  return bytes;
}

function classicCompressedPdf(content = pageContent()): Buffer {
  const compressed = deflateSync(content);
  return buildClassicPdf([
    object(1, "<< /Type /Catalog /Pages 2 0 R >>"),
    object(2, "<< /Type /Pages /Kids [3 0 R] /Count 1 >>"),
    object(3, "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 6 0 R >>"),
    object(4, "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"),
    object(5, String(compressed.length)),
    object(6, streamObject("/Length 5 0 R /Filter [/FlateDecode] /DecodeParms [null]", compressed)),
  ]).bytes;
}

function xrefStreamPdf(): Buffer {
  const content = pageContent();
  const objects = pageObjects(object(5, streamObject(`/Length ${content.length}`, content)));
  return buildXrefStreamPdf(objects, 6);
}

function objectStreamPdf(): Buffer {
  const font = text("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");
  const objectStreamHeader = text("4 0 ");
  const objectStreamBody = Buffer.concat([objectStreamHeader, font]);
  const objectStream = object(5, streamObject(
    `/Type /ObjStm /N 1 /First ${objectStreamHeader.length} /Length ${deflateSync(objectStreamBody).length} /Filter /FlateDecode`,
    deflateSync(objectStreamBody),
  ));
  const objects = [
    object(1, "<< /Type /Catalog /Pages 2 0 R >>"),
    object(2, "<< /Type /Pages /Kids [3 0 R] /Count 1 >>"),
    object(3, "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 6 0 R >>"),
    objectStream,
    object(6, streamObject(`/Length ${pageContent().length}`, pageContent())),
  ];
  let bytes = text("%PDF-1.7\n");
  const offsets = new Map<number, number>();
  for (const entry of objects) {
    offsets.set(entry.id, bytes.length);
    bytes = Buffer.concat([bytes, text(`${entry.id} 0 obj\n`), entry.body, text("\nendobj\n")]);
  }
  const xrefOffset = bytes.length;
  const xrefEntries = [xrefEntry(0, 0, 65535)];
  xrefEntries.push(xrefEntry(1, offsets.get(1)!, 0));
  xrefEntries.push(xrefEntry(1, offsets.get(2)!, 0));
  xrefEntries.push(xrefEntry(1, offsets.get(3)!, 0));
  xrefEntries.push(xrefEntry(2, 5, 0));
  xrefEntries.push(xrefEntry(1, offsets.get(5)!, 0));
  xrefEntries.push(xrefEntry(1, offsets.get(6)!, 0));
  xrefEntries.push(xrefEntry(1, xrefOffset, 0));
  const compressedEntries = deflateSync(Buffer.concat(xrefEntries));
  bytes = Buffer.concat([
    bytes,
    text("7 0 obj\n"),
    streamObject(`/Type /XRef /Size 8 /Root 1 0 R /W [1 4 2] /Index [0 8] /Length ${compressedEntries.length} /Filter /FlateDecode`, compressedEntries),
    text(`\nendobj\nstartxref\n${xrefOffset}\n%%EOF\n`),
  ]);
  return bytes;
}

function compressedJavaScriptObjectStreamPdf(): Buffer {
  const objectStreamHeader = text("4 0 ");
  const objectStreamBody = Buffer.concat([objectStreamHeader, text("<< /S /JavaScript /JS (app.alert) >>")]);
  const compressedObjectStream = deflateSync(objectStreamBody);
  const content = text("q Q");
  const objects = [
    object(1, "<< /Type /Catalog /Pages 2 0 R /OpenAction 4 0 R >>"),
    object(2, "<< /Type /Pages /Kids [3 0 R] /Count 1 >>"),
    object(3, "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 6 0 R >>"),
    object(5, streamObject(`/Type /ObjStm /N 1 /First ${objectStreamHeader.length} /Length ${compressedObjectStream.length} /Filter /FlateDecode`, compressedObjectStream)),
    object(6, streamObject(`/Length ${content.length}`, content)),
  ];
  let bytes = text("%PDF-1.7\n");
  const offsets = new Map<number, number>();
  for (const entry of objects) {
    offsets.set(entry.id, bytes.length);
    bytes = Buffer.concat([bytes, text(`${entry.id} 0 obj\n`), entry.body, text("\nendobj\n")]);
  }
  const xrefOffset = bytes.length;
  const xrefEntries = [
    xrefEntry(0, 0, 65535),
    xrefEntry(1, offsets.get(1)!, 0),
    xrefEntry(1, offsets.get(2)!, 0),
    xrefEntry(1, offsets.get(3)!, 0),
    xrefEntry(2, 5, 0),
    xrefEntry(1, offsets.get(5)!, 0),
    xrefEntry(1, offsets.get(6)!, 0),
    xrefEntry(1, xrefOffset, 0),
  ];
  const compressedEntries = deflateSync(Buffer.concat(xrefEntries));
  bytes = Buffer.concat([
    bytes,
    text("7 0 obj\n"),
    streamObject(`/Type /XRef /Size 8 /Root 1 0 R /W [1 4 2] /Index [0 8] /Length ${compressedEntries.length} /Filter /FlateDecode`, compressedEntries),
    text(`\nendobj\nstartxref\n${xrefOffset}\n%%EOF\n`),
  ]);
  return bytes;
}

function incrementalPdf(): Buffer {
  const content = pageContent();
  const base = buildClassicPdf(pageObjects(object(5, streamObject(`/Length ${content.length}`, content))));
  const updatedCatalog = text("1 1 obj\n<< /Type /Catalog /Pages 2 0 R /Lang (en-US) >>\nendobj\n");
  const info = text("7 0 obj\n<< /Producer (Generated producer update) >>\nendobj\n");
  const updatedCatalogOffset = base.bytes.length;
  const infoOffset = updatedCatalogOffset + updatedCatalog.length;
  const xrefOffset = infoOffset + info.length;
  const xref = text(
    `xref\n1 1\n${String(updatedCatalogOffset).padStart(10, "0")} 00001 n \n`
      + `7 1\n${String(infoOffset).padStart(10, "0")} 00000 n \n`
      + `trailer\n<< /Size 8 /Root 1 1 R /Info 7 0 R /Prev ${base.xrefOffset} >>\n`
      + `startxref\n${xrefOffset}\n%%EOF\n`,
  );
  return Buffer.concat([base.bytes, updatedCatalog, info, xref]);
}

export const syntheticStructurePdfFixtures = [
  { name: "classic compressed stream with indirect length and filter array", bytes: classicCompressedPdf() },
  { name: "compressed cross-reference stream", bytes: xrefStreamPdf() },
  { name: "compressed object stream", bytes: objectStreamPdf() },
  { name: "incremental update with a new catalog generation", bytes: incrementalPdf() },
] as const;

export function syntheticPdfWithHarmlessFeatureName(): Buffer {
  return classicCompressedPdf(pageContent("Harmless text /JavaScript /Launch /RichMedia /XFA"));
}

export function syntheticPdfWithCompressedJavaScript(): Buffer {
  return compressedJavaScriptObjectStreamPdf();
}

export function syntheticPdfWithCatalogFeature(feature: string): Buffer {
  const content = pageContent();
  const baseObjects = pageObjects(object(5, streamObject(`/Length ${content.length}`, content)));
  const catalog = baseObjects.find(({ id }) => id === 1);
  if (!catalog) throw new Error("catalog fixture object is missing");
  const extras: PdfObject[] = [];
  if (feature.includes("/Launch")) {
    catalog.body = text("<< /Type /Catalog /Pages 2 0 R /OpenAction 6 0 R >>");
    extras.push(object(6, "<< /S /Launch /F (payload.bin) >>"));
  } else if (feature.includes("/OpenAction")) {
    catalog.body = text("<< /Type /Catalog /Pages 2 0 R /OpenAction 6 0 R >>");
    extras.push(object(6, "<< /S /JavaScript /JS (app.alert) >>"));
  } else if (feature.includes("/EmbeddedFiles")) {
    catalog.body = text("<< /Type /Catalog /Pages 2 0 R /Names 6 0 R >>");
    extras.push(
      object(6, "<< /EmbeddedFiles 7 0 R >>"),
      object(7, "<< /Names [(payload.bin) 8 0 R] >>"),
      object(8, "<< /Type /Filespec /F (payload.bin) /EF << /F 9 0 R >> >>"),
      object(9, streamObject("/Length 7", text("payload"))),
    );
  } else if (feature.includes("/RichMedia")) {
    catalog.body = text("<< /Type /Catalog /Pages 2 0 R /RichMedia 6 0 R >>");
    extras.push(object(6, "<< /Type /RichMedia >>"));
  } else if (feature.includes("/XFA")) {
    const xfa = text("<template/>");
    catalog.body = text("<< /Type /Catalog /Pages 2 0 R /AcroForm 6 0 R >>");
    extras.push(
      object(6, "<< /XFA 7 0 R >>"),
      object(7, streamObject(`/Length ${xfa.length}`, xfa)),
    );
  } else {
    catalog.body = text(`<< /Type /Catalog /Pages 2 0 R ${feature} >>`);
  }
  return buildClassicPdf([...baseObjects, ...extras]).bytes;
}
