import { deflateSync } from "node:zlib";

/** Synthetic structure fixtures generated by local code; not common-producer output. */

interface PdfObject {
  id: number;
  generation?: number;
  body: Buffer;
}

interface ClassicPdfBuild {
  bytes: Buffer;
  xrefOffset: number;
}

function text(value: string): Buffer {
  return Buffer.from(value, "latin1");
}

function object(id: number, body: Buffer | string, generation = 0): PdfObject {
  return { id, generation, body: typeof body === "string" ? text(body) : body };
}

function streamObject(dictionary: string, body: Buffer): Buffer {
  return Buffer.concat([
    text(`<< ${dictionary} >>\nstream\n`),
    body,
    text("\nendstream"),
  ]);
}

function pageObjects(contents: PdfObject): PdfObject[] {
  return [
    object(1, "<< /Type /Catalog /Pages 2 0 R >>"),
    object(2, "<< /Type /Pages /Kids [3 0 R] /Count 1 >>"),
    object(3, `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents ${contents.id} 0 R >>`),
    object(4, "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"),
    contents,
  ];
}

function pageContent(value = "Generated PDF producer fixture"): Buffer {
  const escaped = value.replaceAll("\\", "\\\\").replaceAll("(", "\\(").replaceAll(")", "\\)");
  return text(`BT /F1 18 Tf 72 720 Td (${escaped}) Tj ET`);
}

function buildClassicPdf(objects: PdfObject[], root = "1 0 R"): ClassicPdfBuild {
  const ordered = [...objects].sort((left, right) => left.id - right.id);
  const offsets = new Map<number, number>([[0, 0]]);
  let bytes = text("%PDF-1.7\n");
  for (const entry of ordered) {
    offsets.set(entry.id, bytes.length);
    bytes = Buffer.concat([
      bytes,
      text(`${entry.id} ${entry.generation ?? 0} obj\n`),
      entry.body,
      text("\nendobj\n"),
    ]);
  }
  const size = Math.max(...ordered.map(({ id }) => id)) + 1;
  const xrefOffset = bytes.length;
  let xref = `xref\n0 ${size}\n0000000000 65535 f \n`;
  for (let id = 1; id < size; id += 1) {
    const offset = offsets.get(id);
    if (offset === undefined) throw new Error(`fixture object ${id} is missing`);
    const generation = ordered.find((entry) => entry.id === id)?.generation ?? 0;
    xref += `${String(offset).padStart(10, "0")} ${String(generation).padStart(5, "0")} n \n`;
  }
  bytes = Buffer.concat([
    bytes,
    text(xref),
    text(`trailer\n<< /Size ${size} /Root ${root} >>\nstartxref\n${xrefOffset}\n%%EOF\n`),
  ]);
  return { bytes, xrefOffset };
}

function xrefEntry(type: number, field2: number, field3: number): Buffer {
  const entry = Buffer.alloc(7);
  entry[0] = type;
  entry.writeUInt32BE(field2, 1);
  entry.writeUInt16BE(field3, 5);
  return entry;
}

function buildXrefStreamPdf(objects: PdfObject[], xrefObjectId: number): Buffer {
  let bytes = text("%PDF-1.7\n");
  const offsets = new Map<number, number>();
  for (const entry of [...objects].sort((left, right) => left.id - right.id)) {
    offsets.set(entry.id, bytes.length);
    bytes = Buffer.concat([
      bytes,
      text(`${entry.id} ${entry.generation ?? 0} obj\n`),
      entry.body,
      text("\nendobj\n"),
    ]);
  }
  const xrefOffset = bytes.length;
  const entries = [xrefEntry(0, 0, 65535)];
  for (let id = 1; id <= xrefObjectId; id += 1) {
    entries.push(xrefEntry(1, id === xrefObjectId ? xrefOffset : offsets.get(id)!, 0));
  }
  const compressedEntries = deflateSync(Buffer.concat(entries));
  const dictionary = `/Type /XRef /Size ${xrefObjectId + 1} /Root 1 0 R /W [1 4 2] /Index [0 ${xrefObjectId + 1}] /Length ${compressedEntries.length} /Filter /FlateDecode`;
  const xrefObject = object(xrefObjectId, streamObject(dictionary, compressedEntries));
  bytes = Buffer.concat([
    bytes,
    text(`${xrefObject.id} 0 obj\n`),
    xrefObject.body,
    text("\nendobj\n"),
    text(`startxref\n${xrefOffset}\n%%EOF\n`),
  ]);
  if (offsets.size !== xrefObjectId - 1) throw new Error("fixture object numbering is not contiguous");
  return bytes;
}

function classicCompressedPdf(content = pageContent()): Buffer {
  const compressed = deflateSync(content);
  return buildClassicPdf([
    object(1, "<< /Type /Catalog /Pages 2 0 R >>"),
    object(2, "<< /Type /Pages /Kids [3 0 R] /Count 1 >>"),
    object(3, "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 6 0 R >>"),
    object(4, "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"),
    object(5, String(compressed.length)),
    object(6, streamObject("/Length 5 0 R /Filter [/FlateDecode] /DecodeParms [null]", compressed)),
  ]).bytes;
}

function xrefStreamPdf(): Buffer {
  const content = pageContent();
  const objects = pageObjects(object(5, streamObject(`/Length ${content.length}`, content)));
  return buildXrefStreamPdf(objects, 6);
}

function objectStreamPdf(): Buffer {
  const font = text("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");
  const objectStreamHeader = text("4 0 ");
  const objectStreamBody = Buffer.concat([objectStreamHeader, font]);
  const objectStream = object(5, streamObject(
    `/Type /ObjStm /N 1 /First ${objectStreamHeader.length} /Length ${deflateSync(objectStreamBody).length} /Filter /FlateDecode`,
    deflateSync(objectStreamBody),
  ));
  const objects = [
    object(1, "<< /Type /Catalog /Pages 2 0 R >>"),
    object(2, "<< /Type /Pages /Kids [3 0 R] /Count 1 >>"),
    object(3, "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 6 0 R >>"),
    objectStream,
    object(6, streamObject(`/Length ${pageContent().length}`, pageContent())),
  ];
  let bytes = text("%PDF-1.7\n");
  const offsets = new Map<number, number>();
  for (const entry of objects) {
    offsets.set(entry.id, bytes.length);
    bytes = Buffer.concat([bytes, text(`${entry.id} 0 obj\n`), entry.body, text("\nendobj\n")]);
  }
  const xrefOffset = bytes.length;
  const xrefEntries = [xrefEntry(0, 0, 65535)];
  xrefEntries.push(xrefEntry(1, offsets.get(1)!, 0));
  xrefEntries.push(xrefEntry(1, offsets.get(2)!, 0));
  xrefEntries.push(xrefEntry(1, offsets.get(3)!, 0));
  xrefEntries.push(xrefEntry(2, 5, 0));
  xrefEntries.push(xrefEntry(1, offsets.get(5)!, 0));
  xrefEntries.push(xrefEntry(1, offsets.get(6)!, 0));
  xrefEntries.push(xrefEntry(1, xrefOffset, 0));
  const compressedEntries = deflateSync(Buffer.concat(xrefEntries));
  bytes = Buffer.concat([
    bytes,
    text("7 0 obj\n"),
    streamObject(`/Type /XRef /Size 8 /Root 1 0 R /W [1 4 2] /Index [0 8] /Length ${compressedEntries.length} /Filter /FlateDecode`, compressedEntries),
    text(`\nendobj\nstartxref\n${xrefOffset}\n%%EOF\n`),
  ]);
  return bytes;
}

function incrementalPdf(): Buffer {
  const content = pageContent();
  const base = buildClassicPdf(pageObjects(object(5, streamObject(`/Length ${content.length}`, content))));
  const updatedCatalog = text("1 1 obj\n<< /Type /Catalog /Pages 2 0 R /Lang (en-US) >>\nendobj\n");
  const info = text("7 0 obj\n<< /Producer (Generated producer update) >>\nendobj\n");
  const updatedCatalogOffset = base.bytes.length;
  const infoOffset = updatedCatalogOffset + updatedCatalog.length;
  const xrefOffset = infoOffset + info.length;
  const xref = text(
    `xref\n1 1\n${String(updatedCatalogOffset).padStart(10, "0")} 00001 n \n`
      + `7 1\n${String(infoOffset).padStart(10, "0")} 00000 n \n`
      + `trailer\n<< /Size 8 /Root 1 1 R /Info 7 0 R /Prev ${base.xrefOffset} >>\n`
      + `startxref\n${xrefOffset}\n%%EOF\n`,
  );
  return Buffer.concat([base.bytes, updatedCatalog, info, xref]);
}

export interface ModernPdfOptions {
  /** Extra catalog entries, written inside the catalog dictionary. */
  catalog?: string;
  /** Extra page entries, written inside the page dictionary. */
  page?: string;
  /** Extra plain objects, packed into the object stream with the catalog and page tree. */
  packed?: Record<number, string>;
  /** Extra top-level streams: id to [dictionary entries, payload]. */
  streams?: Record<number, [string, Buffer]>;
  /** Lists every object as its own /Index subsection, so /Type /XRef lands far from the dictionary's start. */
  longIndex?: boolean;
}

/**
 * The shape current producers write: PDF 1.7 with the catalog, page tree and
 * annotations packed into a Flate object stream, indexed by a compressed
 * cross-reference stream whose dictionary carries a nested /DecodeParms
 * (PNG predictor) ahead of /Size, keys sorted as most writers sort them.
 */
export function syntheticModernPdf(options: ModernPdfOptions = {}): Buffer {
  const content = pageContent();
  const packed: Record<number, string> = {
    1: `<< /Type /Catalog /Pages 2 0 R ${options.catalog ?? ""} >>`,
    2: "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    3: `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R ${options.page ?? ""} >>`,
    4: "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ...options.packed,
  };
  const streams: Record<number, [string, Buffer]> = { 5: ["", content], ...options.streams };
  if (options.longIndex) {
    // Many objects listed one subsection each, as an incremental save writes them.
    const firstFiller = Math.max(...Object.keys(packed).map(Number), ...Object.keys(streams).map(Number)) + 1;
    for (let id = firstFiller; id < firstFiller + 120; id += 1) packed[id] = "<< /Producer (filler) >>";
  }
  const packedIds = Object.keys(packed).map(Number).sort((left, right) => left - right);
  const streamIds = Object.keys(streams).map(Number).sort((left, right) => left - right);
  const objectStreamId = Math.max(...packedIds, ...streamIds) + 1;
  const xrefId = objectStreamId + 1;
  let header = "";
  let body = "";
  for (const id of packedIds) {
    header += `${id} ${body.length} `;
    body += `${packed[id]}\n`;
  }
  const encoded = deflateSync(text(header + body));
  const objectStreamDictionary = "/Type /ObjStm /Filter /FlateDecode";

  let bytes = text("%PDF-1.7\n%\xe2\xe3\xcf\xd3\n");
  const offsets = new Map<number, number>();
  for (const id of streamIds) {
    const [dictionary, payload] = streams[id];
    offsets.set(id, bytes.length);
    bytes = Buffer.concat([bytes, text(`${id} 0 obj\n`), streamObject(`${dictionary} /Length ${payload.length}`, payload), text("\nendobj\n")]);
  }
  offsets.set(objectStreamId, bytes.length);
  bytes = Buffer.concat([
    bytes,
    text(`${objectStreamId} 0 obj\n`),
    streamObject(`${objectStreamDictionary} /N ${packedIds.length} /First ${header.length} /Length ${encoded.length}`, encoded),
    text("\nendobj\n"),
  ]);

  const xrefOffset = bytes.length;
  const rows: Buffer[] = [];
  for (let id = 0; id <= xrefId; id += 1) {
    const row = Buffer.alloc(6);
    if (id in packed) {
      row[0] = 2;
      row.writeUInt32BE(objectStreamId, 1);
      row[5] = packedIds.indexOf(id);
    } else if (id === xrefId || offsets.has(id)) {
      row[0] = 1;
      row.writeUInt32BE(id === xrefId ? xrefOffset : offsets.get(id)!, 1);
    } else {
      row[5] = id === 0 ? 0xff : 0;
    }
    rows.push(row);
  }
  // PNG "Up" predictor, as producers write cross-reference streams.
  const predicted = rows.map((row, index) => Buffer.concat([
    Buffer.from([2]),
    Buffer.from(row.map((value, column) => (value - (index === 0 ? 0 : rows[index - 1][column])) & 0xff)),
  ]));
  const compressedRows = deflateSync(Buffer.concat(predicted));
  const index = options.longIndex
    ? Array.from({ length: xrefId + 1 }, (_, id) => `${id} 1`).join(" ")
    : `0 ${xrefId + 1}`;
  const identifier = "0123456789abcdef0123456789abcdef";
  const xrefDictionary = `/DecodeParms << /Columns 6 /Predictor 12 >> /Filter /FlateDecode /ID [<${identifier}> <${identifier}>] `
    + `/Index [${index}] /Length ${compressedRows.length} /Root 1 0 R /Size ${xrefId + 1} /Type /XRef /W [1 4 1]`;
  return Buffer.concat([
    bytes,
    text(`${xrefId} 0 obj\n`),
    streamObject(xrefDictionary, compressedRows),
    text(`\nendobj\nstartxref\n${xrefOffset}\n%%EOF\n`),
  ]);
}

const javaScriptAction = "<< /S /JavaScript /JS (app.alert\\(1\\)) >>";
const launchAction = "<< /S /Launch /F (payload.exe) >>";

/**
 * Active content and attachments in an otherwise ordinary modern PDF, packed
 * into its object stream as producers write them. Orbit accepts every one
 * (ADR-0033): pdf.js opens the file with scripting and XFA off, so none of it
 * ever runs in Orbit.
 */
export const syntheticPdfActiveContent: ReadonlyArray<{ name: string; options: ModernPdfOptions }> = [
  { name: "document-level JavaScript", options: { catalog: "/Names << /JavaScript 6 0 R >>", packed: { 6: "<< /Names [(run) 7 0 R] >>", 7: javaScriptAction } } },
  { name: "a JavaScript open action", options: { catalog: "/OpenAction 6 0 R", packed: { 6: javaScriptAction } } },
  { name: "a launch open action", options: { catalog: "/OpenAction 6 0 R", packed: { 6: launchAction } } },
  { name: "a link annotation running JavaScript", options: { page: "/Annots [6 0 R]", packed: { 6: "<< /Type /Annot /Subtype /Link /Rect [0 0 99 99] /A 7 0 R >>", 7: javaScriptAction } } },
  { name: "a form field with a keystroke script", options: { catalog: "/AcroForm << /Fields [6 0 R] >>", page: "/Annots [6 0 R]", packed: { 6: "<< /Type /Annot /Subtype /Widget /FT /Tx /T (field) /Rect [0 0 99 20] /P 3 0 R /AA << /K 7 0 R >> >>", 7: javaScriptAction } } },
  { name: "an XFA form", options: { catalog: "/AcroForm << /Fields [] /XFA 6 0 R >>", streams: { 6: ["", text("<xdp:xdp xmlns:xdp=\"http://ns.adobe.com/xdp/\"><template/></xdp:xdp>")] } } },
  { name: "an embedded file", options: { catalog: "/Names << /EmbeddedFiles 6 0 R >>", packed: { 6: "<< /Names [(payload.bin) 7 0 R] >>", 7: "<< /Type /Filespec /F (payload.bin) /EF << /F 8 0 R >> >>" }, streams: { 8: ["", text("payload")] } } },
];

/** A PDF with `pages` pages sharing one content stream, for the page cap. */
export function syntheticPdfWithPages(pages: number): Buffer {
  const content = pageContent();
  const kids = Array.from({ length: pages }, (_, index) => `${index + 6} 0 R`).join(" ");
  const objects = [
    object(1, "<< /Type /Catalog /Pages 2 0 R >>"),
    object(2, `<< /Type /Pages /Kids [${kids}] /Count ${pages} >>`),
    object(4, "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"),
    object(5, streamObject(`/Length ${content.length}`, content)),
    ...Array.from({ length: pages }, (_, index) => object(index + 6, "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>")),
  ];
  objects.push(object(3, "<< /Producer (page cap fixture) >>"));
  return buildClassicPdf(objects).bytes;
}

export const syntheticStructurePdfFixtures = [
  { name: "classic compressed stream with indirect length and filter array", bytes: classicCompressedPdf() },
  { name: "compressed cross-reference stream", bytes: xrefStreamPdf() },
  { name: "compressed object stream", bytes: objectStreamPdf() },
  { name: "incremental update with a new catalog generation", bytes: incrementalPdf() },
] as const;
