"use client";
import { useEffect, useState } from "react";

type Inbox = { receipts: Array<{ id: string; status: string; householdId: string | null; draftVersion: number; proposal: Record<string, unknown>; fieldEvidence: Record<string, unknown>; expiresAt: string; receivedAt: string; attachmentCount: number }>; households: Array<{ id: string; name: string; sections: Array<{ id: string; name: string }> }> };
export function ImapInbox({ csrfToken }: { csrfToken: string }) {
  const [inbox, setInbox] = useState<Inbox | null>(null); const [error, setError] = useState("");
  const load = async () => { try { const response = await fetch("/api/imap-inbox", { credentials: "same-origin" }); if (!response.ok) throw new Error("Could not load incoming documents"); setInbox(await response.json() as Inbox); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not load incoming documents"); } };
  useEffect(() => { let cancelled = false; fetch("/api/imap-inbox", { credentials: "same-origin" }).then(async (response) => { if (!response.ok) throw new Error("Could not load incoming documents"); return response.json() as Promise<Inbox>; }).then((payload) => { if (!cancelled) setInbox(payload); }).catch((caught: unknown) => { if (!cancelled) setError(caught instanceof Error ? caught.message : "Could not load incoming documents"); }); return () => { cancelled = true; }; }, []);
  const assign = async (id: string, householdId: string) => { const response = await fetch(`/api/imap-inbox/${id}`, { method: "PUT", credentials: "same-origin", headers: { "Content-Type": "application/json", "X-CSRF-Token": csrfToken }, body: JSON.stringify({ householdId }) }); if (!response.ok) { setError("Could not assign that incoming document"); return; } void load(); };
  const discard = async (id: string) => { if (!window.confirm("Discard this incoming document? Its stored files will be scheduled for deletion.")) return; const response = await fetch(`/api/imap-inbox/${id}`, { method: "DELETE", credentials: "same-origin", headers: { "X-CSRF-Token": csrfToken } }); if (!response.ok) { setError("Could not discard that incoming document"); return; } void load(); };
  return <section className="settings-content"><div className="setting-heading"><h3>Incoming documents</h3><p>Incoming documents remain private until you explicitly review and approve their final values.</p></div>{error && <p role="alert">{error}</p>}{!inbox ? <p>Loading incoming documents…</p> : inbox.receipts.length === 0 ? <p>No incoming documents waiting for review.</p> : <div className="admin-list">{inbox.receipts.map((receipt) => <article key={receipt.id}><span><strong>{receipt.attachmentCount} attachment{receipt.attachmentCount === 1 ? "" : "s"}</strong><small>Received {new Date(receipt.receivedAt).toLocaleString()}</small></span><div>{!receipt.householdId ? <select aria-label="Choose household" defaultValue="" onChange={(event) => event.target.value && void assign(receipt.id, event.target.value)}><option value="" disabled>Choose household…</option>{inbox.households.map((household) => <option key={household.id} value={household.id}>{household.name}</option>)}</select> : <b>Ready for explicit approval</b>}<button type="button" onClick={() => void discard(receipt.id)}>Discard</button></div></article>)}</div>}</section>;
}
